language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - ruby-head
  - jruby-head
  - rbx-2

before_install:
  - gem install bundler -v 1.10.4
  - gem update --system
  - gem --version

gemfile:
  - Gemfile

script: bundle exec rspec spec

notifications:
  email: false
